//ISSUE
export const ADD_ISSUES = 'ADD_ISSUES';
export const ADD_ISSUE = 'ADD_ISSUE';
export const SAVE_ISSUE = 'SAVE_ISSUE';
export const SET_ISSUE_FILTER = 'SET_ISSUE_FILTER';
export const SET_ACTIVE_ISSUE = 'SET_ACTIVE_ISSUE';
export const SORT_ISSUES = 'SORT_ISSUES';
export const TOGGLE_CHECKED_ISSUE = 'TOGGLE_CHECKED_ISSUE';
export const ADD_ISSUE_TO_BATCH = 'ADD_ISSUE_TO_BATCH';
export const BATCH_ISSUES = 'BATCH_ISSUES';
export const TOGGLE_AREA = 'TOGGLE_AREA';
//USER
export const SET_USER = 'SET_USER';
export const SAVE_USER = 'SAVE_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const ADD_ASSIGNEES = 'ADD_ASSIGNEES';
export const LOGOUT_USER = 'LOGOUT_USER';
//MODALS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
//PROJECT
export const ADD_PROJECTS = 'ADD_PROJECTS';
//COMMENT
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
//FILE
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
