export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_ISSUE_FILTER = 'SET_ISSUE_FILTER';

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const CHANGE_ISSUE_STATUS = 'CHANGE_ISSUE_STATUS';
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS';
export const SAVE_ISSUE_SUCCESS = 'SAVE_ISSUE_SUCCESS';
export const SET_ACTIVE_ISSUE = 'SET_ACTIVE_ISSUE';
export const SORT_ISSUES = 'SORT_ISSUES';